# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
      - pip install poetry
      - poetry install --with dev
      - cd docs
      - poetry run make $READTHEDOCS_OUTPUT/html
