name: publish
on:
  release:
    types:  [published]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install poetry
          run: pipx install poetry
        - uses: actions/setup-python@v5
          with:
            python-version: '3.13'
            cache: 'poetry'
        - run: poetry install --with dev
        - name: Build package
          run: poetry build
        - name: Publish Package
          run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
